export interface GenreDefinition {
  id: string;
  label: { 'pt-BR': string; 'en-US': string };
  apiGenres: string[];
  accent: string;
}

export const GENRES: GenreDefinition[] = [
  { id: 'action', label: { 'pt-BR': 'Ação e aventura', 'en-US': 'Action & adventure' }, apiGenres: ['Action', 'Adventure'], accent: '#e84b32' },
  { id: 'comedy', label: { 'pt-BR': 'Comédia', 'en-US': 'Comedy' }, apiGenres: ['Comedy'], accent: '#ffd447' },
  { id: 'horror', label: { 'pt-BR': 'Terror', 'en-US': 'Horror' }, apiGenres: ['Horror'], accent: '#9d3ec5' },
  { id: 'scifi', label: { 'pt-BR': 'Ficção e fantasia', 'en-US': 'Sci-fi & fantasy' }, apiGenres: ['Sci-Fi', 'Fantasy'], accent: '#42cbd3' },
  { id: 'drama', label: { 'pt-BR': 'Drama', 'en-US': 'Drama' }, apiGenres: ['Drama'], accent: '#df735b' },
  { id: 'crime', label: { 'pt-BR': 'Crime e suspense', 'en-US': 'Crime & thriller' }, apiGenres: ['Crime', 'Thriller', 'Mystery'], accent: '#7590af' },
  { id: 'romance', label: { 'pt-BR': 'Romance', 'en-US': 'Romance' }, apiGenres: ['Romance'], accent: '#ed7aa8' },
  { id: 'family', label: { 'pt-BR': 'Família e animação', 'en-US': 'Family & animation' }, apiGenres: ['Family', 'Animation'], accent: '#68b46a' },
  { id: 'documentary', label: { 'pt-BR': 'Documentário', 'en-US': 'Documentary' }, apiGenres: ['Documentary'], accent: '#be955e' },
];

export type Locale = 'pt-BR' | 'en-US';

export const copy = {
  'pt-BR': {
    tagline: 'A magia da locadora no seu player.',
    intro: 'Escolha suas fitas, monte a Cesta e leve até o Balcão. Até 3 aluguéis ativos.',
    genre: 'Gênero',
    type: 'Formato',
    movies: 'Filmes',
    series: 'Séries',
    year: 'Ano da loja',
    go: 'Ir',
    search: 'Pesquisar na estante',
    basket: 'Cesta',
    counter: 'Balcão',
    rent: 'Alugar',
    rentHint: 'Escolha quais fitas levar e confirme no Balcão.',
    account: 'Conta',
    settings: 'Ajustes',
    aisle: 'Corredor',
    tapesFound: 'fitas encontradas',
    loading: 'Abrindo as caixas…',
    retry: 'Verificar o depósito',
    empty: 'Esta prateleira voltou vazia.',
    loadMore: 'Carregar outra estante',
    inspect: 'Inspecionar',
    addBasket: 'Colocar na Cesta',
    removeBasket: 'Retirar da Cesta',
    watchDevelopment: 'Assistir — integração em desenvolvimento',
    demo: 'Acervo de demonstração',
    live: 'Acervo público',
    development: 'Em desenvolvimento',
    close: 'Fechar',
    basketEmpty: 'Sua Cesta está vazia.',
    basketHint: 'Separe até 3 fitas antes de ir ao Balcão.',
    checkoutLater: 'O aluguel com sua conta entra na Fase 2.',
    savedLater: 'Assistir depois e Favoritos entram na Fase 2.',
    accountLater: 'Conta, aluguéis e avaliações entram na Fase 2.',
  },
  'en-US': {
    tagline: 'The video-store magic, in your player.',
    intro: 'Choose your tapes, fill the Basket, and take them to the Counter. Up to 3 active rentals.',
    genre: 'Genre',
    type: 'Format',
    movies: 'Movies',
    series: 'Series',
    year: 'Store year',
    go: 'Go',
    search: 'Search this shelf',
    basket: 'Basket',
    counter: 'Counter',
    rent: 'Rent',
    rentHint: 'Pick the tapes to take and confirm at the counter.',
    account: 'Account',
    settings: 'Settings',
    aisle: 'Aisle',
    tapesFound: 'tapes found',
    loading: 'Opening the boxes…',
    retry: 'Check the stockroom',
    empty: 'This shelf came back empty.',
    loadMore: 'Load another stand',
    inspect: 'Inspect',
    addBasket: 'Add to Basket',
    removeBasket: 'Remove from Basket',
    watchDevelopment: 'Watch — integration in development',
    demo: 'Demo catalogue',
    live: 'Public catalogue',
    development: 'In development',
    close: 'Close',
    basketEmpty: 'Your Basket is empty.',
    basketHint: 'Set aside up to 3 tapes before going to the Counter.',
    checkoutLater: 'Account rentals arrive in Phase 2.',
    savedLater: 'Watch Later and Favorites arrive in Phase 2.',
    accountLater: 'Account, rentals, and reviews arrive in Phase 2.',
  },
} as const;
